name: sensor_sentinel
description: A new Flutter project for ground truth data collection.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.0.0
  provider: ^6.1.1
  crypto: ^3.0.3
  geolocator: ^13.0.2
  permission_handler: ^12.0.1
  h3_flutter: ^0.7.1
  shared_preferences: ^2.5.4
  uuid: ^4.5.2
  share_plus: ^12.0.1
  wakelock_plus: ^1.4.0
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  sensors_plus: ^6.1.1
  noise_meter: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.24.0

flutter:
  uses-material-design: true
